### ISSUE TITLE
single picture with no rollover cannot be enlarged by clicking

### ISSUE THREAD

**Issue by Joyananda** [shadesoflight/tumblr-template-sass#17]
just stays 2D on the page.

**Comment by shadesoflight** [comment]
https://github.com/shadesoflight/tumblr-template-sass/commit/bfd61961f1c1ebc768a36dc90c58024b6701d36e

**Comment by shadesoflight** [comment]
https://github.com/shadesoflight/tumblr-template-sass/commit/bfd61961f1c1ebc768a36dc90c58024b6701d36e
