### ISSUE TITLE
Side Bar Menu With Games In A List

### ISSUE THREAD

**Issue by Joyananda** [shadesoflight/tumblr-template-sass#19]
For something like this, would it be something i could add to myself whenever i need to, or would i have to put in a ticket for a new add to the list when i have to add a new game? Just curious.

**Comment by Joyananda** [comment]
This is the same thing i posted about just now, sorry about that.

**Comment by shadesoflight** [comment]
Duplicate of https://github.com/shadesoflight/tumblr-template-sass/issues/33
